# Site configuration for a fake observatory.
hub:

  wamp_server: ws://localhost:8001/ws
  wamp_http: http://localhost:8001/call
  wamp_realm: test_realm
  address_root: observatory

hosts:

  PSD-KDHGVC639J: {
    # Directory for logs.
       'log-dir': '/Users/sanuma/log/ocs/',

    # Agents running directly on the host machine
    # Note: We aren't going to run this Agent in the quickstart example,
    #       but this gives a good example of configuring an agent directly
    #       on the host
      'agent-instances': [
      {'agent-class': 'GalilAxisControllerAgent',
       'instance-id': 'satcouplingoptics',
       'arguments': ['--ip', '10.120.1.12', # 10.139
                     '--configfile', '/Users/sanuma/git/ocs-site-configs/newconfig_EF.yaml',
                     '--mode', 'acq']},
    ]
     }

  PSD-KDHGVC639J-docker: {
    # Address of crossbar within Docker (based on service name)
    'wamp_server': 'ws://crossbar:8001/ws',
        'wamp_http': 'http://crossbar:8001/call',

    # Agents running within Docker containers
      'agent-instances': [
      {'agent-class': 'InfluxDBAgent',
       'instance-id': 'influxagent',
       'arguments': ['--initial-state', 'record']},
    #  {'agent-class': 'FakeDataAgent',
    #   'instance-id': 'fake-data1',
    #   'arguments': ['--mode', 'acq',
    #                 '--num-channels', '16',
    #                 '--sample-rate', '4']},
    #]
    # }

         #'agent-instances': [
        {'agent-class': 'GalilAxisControllerAgent',
        'instance-id': 'satcouplingoptics',
        'arguments': ['--ip', '10.120.1.12', # 10.139
                      '--configfile', '/config/newconfig_EF.yaml',
                      '--mode', 'acq']},
        ]
          }
